=begin
#用户全部 API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'date'
require 'time'

module ZSGFClient
  class GrantRequest
    # 返回地址。默认无限制，也可在【安全-开放认证网址白名单】配置
    attr_accessor :redirect_uri

    # 授权类型。可选：email、phone、unionid、account
    attr_accessor :grant_type

    # 自定义授权范围，用英文空格分隔
    attr_accessor :scopes

    # 用户名。授权类型为：email/phone/account必填
    attr_accessor :user_name

    # 登录密码。授权类型为：email/phone/account必填
    attr_accessor :password

    # unionId。授权类型为：unionid必填
    attr_accessor :union_id

    # 平台。授权类型为：unionid必填
    attr_accessor :platform

    # 授权有效期。1~99天
    attr_accessor :expire_in_days

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'redirect_uri' => :'redirect_uri',
        :'grant_type' => :'grant_type',
        :'scopes' => :'scopes',
        :'user_name' => :'userName',
        :'password' => :'password',
        :'union_id' => :'unionId',
        :'platform' => :'platform',
        :'expire_in_days' => :'expireInDays'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'redirect_uri' => :'String',
        :'grant_type' => :'String',
        :'scopes' => :'String',
        :'user_name' => :'String',
        :'password' => :'String',
        :'union_id' => :'String',
        :'platform' => :'String',
        :'expire_in_days' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'redirect_uri',
        :'user_name',
        :'password',
        :'union_id',
        :'platform',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ZSGFClient::GrantRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ZSGFClient::GrantRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'redirect_uri')
        self.redirect_uri = attributes[:'redirect_uri']
      end

      if attributes.key?(:'grant_type')
        self.grant_type = attributes[:'grant_type']
      else
        self.grant_type = nil
      end

      if attributes.key?(:'scopes')
        self.scopes = attributes[:'scopes']
      else
        self.scopes = nil
      end

      if attributes.key?(:'user_name')
        self.user_name = attributes[:'user_name']
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      end

      if attributes.key?(:'union_id')
        self.union_id = attributes[:'union_id']
      end

      if attributes.key?(:'platform')
        self.platform = attributes[:'platform']
      end

      if attributes.key?(:'expire_in_days')
        self.expire_in_days = attributes[:'expire_in_days']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @grant_type.nil?
        invalid_properties.push('invalid value for "grant_type", grant_type cannot be nil.')
      end

      if @grant_type.to_s.length < 1
        invalid_properties.push('invalid value for "grant_type", the character length must be great than or equal to 1.')
      end

      pattern = Regexp.new(/^(email|phone|unionid|account)$/)
      if @grant_type !~ pattern
        invalid_properties.push("invalid value for \"grant_type\", must conform to the pattern #{pattern}.")
      end

      if @scopes.nil?
        invalid_properties.push('invalid value for "scopes", scopes cannot be nil.')
      end

      if @scopes.to_s.length < 1
        invalid_properties.push('invalid value for "scopes", the character length must be great than or equal to 1.')
      end

      if !@expire_in_days.nil? && @expire_in_days > 99
        invalid_properties.push('invalid value for "expire_in_days", must be smaller than or equal to 99.')
      end

      if !@expire_in_days.nil? && @expire_in_days < 1
        invalid_properties.push('invalid value for "expire_in_days", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @grant_type.nil?
      return false if @grant_type.to_s.length < 1
      return false if @grant_type !~ Regexp.new(/^(email|phone|unionid|account)$/)
      return false if @scopes.nil?
      return false if @scopes.to_s.length < 1
      return false if !@expire_in_days.nil? && @expire_in_days > 99
      return false if !@expire_in_days.nil? && @expire_in_days < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] grant_type Value to be assigned
    def grant_type=(grant_type)
      if grant_type.nil?
        fail ArgumentError, 'grant_type cannot be nil'
      end

      if grant_type.to_s.length < 1
        fail ArgumentError, 'invalid value for "grant_type", the character length must be great than or equal to 1.'
      end

      pattern = Regexp.new(/^(email|phone|unionid|account)$/)
      if grant_type !~ pattern
        fail ArgumentError, "invalid value for \"grant_type\", must conform to the pattern #{pattern}."
      end

      @grant_type = grant_type
    end

    # Custom attribute writer method with validation
    # @param [Object] scopes Value to be assigned
    def scopes=(scopes)
      if scopes.nil?
        fail ArgumentError, 'scopes cannot be nil'
      end

      if scopes.to_s.length < 1
        fail ArgumentError, 'invalid value for "scopes", the character length must be great than or equal to 1.'
      end

      @scopes = scopes
    end

    # Custom attribute writer method with validation
    # @param [Object] expire_in_days Value to be assigned
    def expire_in_days=(expire_in_days)
      if expire_in_days.nil?
        fail ArgumentError, 'expire_in_days cannot be nil'
      end

      if expire_in_days > 99
        fail ArgumentError, 'invalid value for "expire_in_days", must be smaller than or equal to 99.'
      end

      if expire_in_days < 1
        fail ArgumentError, 'invalid value for "expire_in_days", must be greater than or equal to 1.'
      end

      @expire_in_days = expire_in_days
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          redirect_uri == o.redirect_uri &&
          grant_type == o.grant_type &&
          scopes == o.scopes &&
          user_name == o.user_name &&
          password == o.password &&
          union_id == o.union_id &&
          platform == o.platform &&
          expire_in_days == o.expire_in_days
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [redirect_uri, grant_type, scopes, user_name, password, union_id, platform, expire_in_days].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ZSGFClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
