=begin
#全部  API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'cgi'

module ZSGFClient
  class SystemFileApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # 创建文件夹
    # 根据指定路径创建文件夹
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 文件夹路径
    # @return [BooleanApiResponse]
    def system_file_create_folder(opts = {})
      data, _status_code, _headers = system_file_create_folder_with_http_info(opts)
      data
    end

    # 创建文件夹
    # 根据指定路径创建文件夹
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 文件夹路径
    # @return [Array<(BooleanApiResponse, Integer, Hash)>] BooleanApiResponse data, response status code and response headers
    def system_file_create_folder_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SystemFileApi.system_file_create_folder ...'
      end
      # resource path
      local_var_path = '/SystemFile/CreateFolder'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'path'] = opts[:'path'] if !opts[:'path'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'BooleanApiResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"SystemFileApi.system_file_create_folder",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemFileApi#system_file_create_folder\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 删除文件
    # 根据指定路径删除文件
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 文件路径
    # @return [BooleanApiResponse]
    def system_file_delete(opts = {})
      data, _status_code, _headers = system_file_delete_with_http_info(opts)
      data
    end

    # 删除文件
    # 根据指定路径删除文件
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 文件路径
    # @return [Array<(BooleanApiResponse, Integer, Hash)>] BooleanApiResponse data, response status code and response headers
    def system_file_delete_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SystemFileApi.system_file_delete ...'
      end
      # resource path
      local_var_path = '/SystemFile'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'path'] = opts[:'path'] if !opts[:'path'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'BooleanApiResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"SystemFileApi.system_file_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemFileApi#system_file_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 重命名文件
    # 根据指定的源文件名和目标文件名重命名文件
    # @param [Hash] opts the optional parameters
    # @option opts [String] :source_name 源文件名
    # @option opts [String] :dest_name 目标文件名
    # @return [BooleanApiResponse]
    def system_file_rename(opts = {})
      data, _status_code, _headers = system_file_rename_with_http_info(opts)
      data
    end

    # 重命名文件
    # 根据指定的源文件名和目标文件名重命名文件
    # @param [Hash] opts the optional parameters
    # @option opts [String] :source_name 源文件名
    # @option opts [String] :dest_name 目标文件名
    # @return [Array<(BooleanApiResponse, Integer, Hash)>] BooleanApiResponse data, response status code and response headers
    def system_file_rename_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SystemFileApi.system_file_rename ...'
      end
      # resource path
      local_var_path = '/SystemFile/Rename'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'sourceName'] = opts[:'source_name'] if !opts[:'source_name'].nil?
      query_params[:'destName'] = opts[:'dest_name'] if !opts[:'dest_name'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'BooleanApiResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"SystemFileApi.system_file_rename",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemFileApi#system_file_rename\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 上传文件
    # 根据指定路径上传文件
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 上传的路径
    # @option opts [File] :file 上传的文件
    # @return [StringApiResponse]
    def system_file_upload(opts = {})
      data, _status_code, _headers = system_file_upload_with_http_info(opts)
      data
    end

    # 上传文件
    # 根据指定路径上传文件
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 上传的路径
    # @option opts [File] :file 上传的文件
    # @return [Array<(StringApiResponse, Integer, Hash)>] StringApiResponse data, response status code and response headers
    def system_file_upload_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SystemFileApi.system_file_upload ...'
      end
      # resource path
      local_var_path = '/SystemFile'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'path'] = opts[:'path'] if !opts[:'path'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}
      form_params['file'] = opts[:'file'] if !opts[:'file'].nil?

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'StringApiResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"SystemFileApi.system_file_upload",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemFileApi#system_file_upload\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 获取文件列表
    # 根据指定路径获取文件列表
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 文件路径
    # @return [SystemFileListResultApiResponse]
    def system_files(opts = {})
      data, _status_code, _headers = system_files_with_http_info(opts)
      data
    end

    # 获取文件列表
    # 根据指定路径获取文件列表
    # @param [Hash] opts the optional parameters
    # @option opts [String] :path 文件路径
    # @return [Array<(SystemFileListResultApiResponse, Integer, Hash)>] SystemFileListResultApiResponse data, response status code and response headers
    def system_files_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SystemFileApi.system_files ...'
      end
      # resource path
      local_var_path = '/SystemFile'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'path'] = opts[:'path'] if !opts[:'path'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SystemFileListResultApiResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"SystemFileApi.system_files",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SystemFileApi#system_files\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
