=begin
#用户全部 API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ZSGFClient::AlipayApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AlipayApi' do
  before do
    # run before each test
    @api_instance = ZSGFClient::AlipayApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlipayApi' do
    it 'should create an instance of AlipayApi' do
      expect(@api_instance).to be_instance_of(ZSGFClient::AlipayApi)
    end
  end

  # unit tests for alipay_create_order
  # 创建当面付订单
  # 创建一个当面付订单，并返回支付二维码。
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [AlipayCreateOrderRequest] :alipay_create_order_request 
  # @return [StringApiResponse]
  describe 'alipay_create_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for alipay_create_order_page_pay
  # 创建PC支付订单
  # 创建一个PC支付订单，并返回支付页面。
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [AlipayCreateOrderPagePayRequest] :alipay_create_order_page_pay_request 
  # @return [StringApiResponse]
  describe 'alipay_create_order_page_pay test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for alipay_create_order_wap_pay
  # 创建WAP支付订单
  # 创建一个WAP支付订单，并返回支付页面。
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [AlipayCreateOrderWapPayRequest] :alipay_create_order_wap_pay_request 
  # @return [StringApiResponse]
  describe 'alipay_create_order_wap_pay test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for alipay_order_detail
  # 获取订单详情
  # 查询订单详情，包括订单状态和支付信息。
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order_no 订单号
  # @return [AlipayTradeQueryResponseApiResponse]
  describe 'alipay_order_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for alipay_order_refund
  # 发起订单退款
  # 对指定订单进行退款操作。
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :amount 退款金额
  # @option opts [String] :order_no 订单号
  # @return [AlipayTradeRefundResponseApiResponse]
  describe 'alipay_order_refund test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for alipay_return_page_notify
  # 支付成功回调通知
  # 处理支付宝支付成功的同步通知。
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [ReturnPageNotifyRequest] :return_page_notify_request 
  # @return [BooleanApiResponse]
  describe 'alipay_return_page_notify test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
