=begin
#用户全部 API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ZSGFClient::AppApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AppApi' do
  before do
    # run before each test
    @api_instance = ZSGFClient::AppApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AppApi' do
    it 'should create an instance of AppApi' do
      expect(@api_instance).to be_instance_of(ZSGFClient::AppApi)
    end
  end

  # unit tests for app_info
  # 应用详情
  # 根据应用Key获取应用的详细信息和属性。
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :prop_code 属性代码
  # @return [AppInfoResultApiResponse]
  describe 'app_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
