=begin
#用户全部 API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ZSGFClient::FileApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FileApi' do
  before do
    # run before each test
    @api_instance = ZSGFClient::FileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileApi' do
    it 'should create an instance of FileApi' do
      expect(@api_instance).to be_instance_of(ZSGFClient::FileApi)
    end
  end

  # unit tests for file_create_folder
  # 创建文件夹
  # 在指定路径创建文件夹
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :path 文件夹路径
  # @return [BooleanApiResponse]
  describe 'file_create_folder test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for file_delete
  # 删除文件 / 文件夹
  # 根据指定路径删除文件或文件夹
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :path 文件 / 文件夹路径
  # @return [BooleanApiResponse]
  describe 'file_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for file_rename
  # 重命名文件 / 文件夹
  # 将指定的文件或文件夹重命名
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :source_name 原文件 / 文件夹名称
  # @option opts [String] :dest_name 新文件 / 文件夹名称
  # @return [BooleanApiResponse]
  describe 'file_rename test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for file_upload
  # 上传文件
  # 将文件上传到指定路径
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :path 文件夹路径
  # @option opts [File] :file 上传的文件
  # @return [StringApiResponse]
  describe 'file_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for files
  # 获取文件列表
  # 根据指定路径获取文件和文件夹列表
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :path 文件路径
  # @option opts [Integer] :skip 跳过的记录数
  # @option opts [Integer] :take 获取的记录数
  # @return [FileListResultApiResponse]
  describe 'files test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
