=begin
#用户全部 API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ZSGFClient::StorageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StorageApi' do
  before do
    # run before each test
    @api_instance = ZSGFClient::StorageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StorageApi' do
    it 'should create an instance of StorageApi' do
      expect(@api_instance).to be_instance_of(ZSGFClient::StorageApi)
    end
  end

  # unit tests for storage_aggregate
  # 聚合查询
  # 根据聚合管道查询指定表中的数据
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :pipeline 构建聚合查询
  # @return [ObjectListApiResponse]
  describe 'storage_aggregate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_delete
  # 删除数据
  # 删除指定表中指定ID的数据
  # @param table 表名称
  # @param id 数据ID
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [BooleanApiResponse]
  describe 'storage_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_detail
  # 数据详情
  # 获取指定表中指定ID的数据详情
  # @param table 表名称
  # @param id 数据ID
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :project json格式
  # @return [ObjectApiResponse]
  describe 'storage_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_list
  # 查询数据
  # 根据条件查询指定表中的数据
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 过滤，json格式
  # @option opts [String] :project 字段映射，json格式
  # @option opts [String] :sort 排序，json格式
  # @option opts [Time] :start_time 开始时间
  # @option opts [Time] :end_time 结束时间
  # @option opts [Boolean] :explain 查看执行计划
  # @option opts [Integer] :take 默认为10
  # @option opts [Integer] :skip 默认为0
  # @return [StorageListResultApiResponse]
  describe 'storage_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_post
  # 添加数据
  # 向指定表中添加数据，可以是单个json对象或json数组
  # @param table 表名称（小写字母加数字,1-50位）
  # @param app_key 
  # @param request_body json对象 / json数组
  # @param [Hash] opts the optional parameters
  # @return [StringApiResponse]
  describe 'storage_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_put
  # 更新数据
  # 更新指定表中指定ID的数据，可以选择全量更新或部分更新
  # @param table 表名称
  # @param id 数据ID
  # @param app_key 
  # @param request_body json格式
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :replace 是否为全量更新，默认为false
  # @return [BooleanApiResponse]
  describe 'storage_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
