=begin
#全部  API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ZSGFClient::StorageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StorageApi' do
  before do
    # run before each test
    @api_instance = ZSGFClient::StorageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StorageApi' do
    it 'should create an instance of StorageApi' do
      expect(@api_instance).to be_instance_of(ZSGFClient::StorageApi)
    end
  end

  # unit tests for storage_aggregate
  # 聚合查询
  # 根据聚合管道查询指定表中的数据
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :pipeline 构建聚合查询
  # @return [ObjectListApiResponse]
  describe 'storage_aggregate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_clear
  # 清空表数据
  # 根据筛选条件清空指定表中的数据
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 筛选条件，json格式
  # @return [Int64ApiResponse]
  describe 'storage_clear test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_delete
  # 删除数据
  # 删除指定表中指定ID的数据
  # @param table 表名称
  # @param id 数据ID
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [BooleanApiResponse]
  describe 'storage_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_delete_index
  # 删除索引
  # 删除指定表的指定索引
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :index_name 索引名称
  # @return [BooleanApiResponse]
  describe 'storage_delete_index test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_detail
  # 数据详情
  # 获取指定表中指定ID的数据详情
  # @param table 表名称
  # @param id 数据ID
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :project json格式
  # @return [ObjectApiResponse]
  describe 'storage_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_execute_function
  # 执行函数
  # 执行指定的函数
  # @param nonce 随机字符串
  # @param timestamp 时间戳
  # @param signature 签名
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [ExecuteFunctionRequest] :execute_function_request 函数请求参数
  # @return [ObjectApiResponse]
  describe 'storage_execute_function test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_export
  # 导出数据
  # 根据筛选条件导出指定表中的数据
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 筛选条件，json格式
  # @option opts [Time] :start_time 开始时间
  # @option opts [Time] :end_time 结束时间
  # @return [File]
  describe 'storage_export test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_import
  # 导入数据
  # 从文件导入数据到指定表中
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [File] :file 导入的文件
  # @return [BooleanApiResponse]
  describe 'storage_import test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_indexes
  # 获取索引
  # 获取指定表的索引列表
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [ObjectListApiResponse]
  describe 'storage_indexes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_list
  # 查询数据
  # 根据条件查询指定表中的数据
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter 过滤，json格式
  # @option opts [String] :project 字段映射，json格式
  # @option opts [String] :sort 排序，json格式
  # @option opts [Time] :start_time 开始时间
  # @option opts [Time] :end_time 结束时间
  # @option opts [Boolean] :explain 查看执行计划
  # @option opts [Integer] :take 默认为10
  # @option opts [Integer] :skip 默认为0
  # @return [StorageListResultApiResponse]
  describe 'storage_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_post
  # 添加数据
  # 向指定表中添加数据，可以是单个json对象或json数组
  # @param table 表名称（小写字母加数字,1-50位）
  # @param app_key 
  # @param request_body json对象 / json数组
  # @param [Hash] opts the optional parameters
  # @return [StringApiResponse]
  describe 'storage_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_post_index
  # 添加索引
  # 为指定表添加索引
  # @param table 表名称（小写字母加数字,1-50位）
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [PostIndexRequest] :post_index_request json对象 / json数组
  # @return [StringApiResponse]
  describe 'storage_post_index test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_put
  # 更新数据
  # 更新指定表中指定ID的数据，可以选择全量更新或部分更新
  # @param table 表名称
  # @param id 数据ID
  # @param app_key 
  # @param body json格式
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :replace 是否为全量更新，默认为false
  # @return [BooleanApiResponse]
  describe 'storage_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_remove
  # 删除表
  # 删除指定表
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [BooleanApiResponse]
  describe 'storage_remove test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_stats
  # 数据表统计
  # 获取指定表的数据统计信息
  # @param table 表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [ObjectApiResponse]
  describe 'storage_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for storage_tables
  # 获取数据表
  # 获取当前应用的所有数据表名称
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [StringListApiResponse]
  describe 'storage_tables test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
