=begin
#全部  API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ZSGFClient::UserSettingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserSettingApi' do
  before do
    # run before each test
    @api_instance = ZSGFClient::UserSettingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserSettingApi' do
    it 'should create an instance of UserSettingApi' do
      expect(@api_instance).to be_instance_of(ZSGFClient::UserSettingApi)
    end
  end

  # unit tests for user_setting
  # 获取用户配置项详情
  # 根据配置项ID获取用户配置项详情
  # @param id 配置项ID
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [UserSettingApiResponse]
  describe 'user_setting test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_setting_delete
  # 删除用户配置项
  # 根据配置项ID删除用户配置项
  # @param id 配置项ID
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @return [BooleanApiResponse]
  describe 'user_setting_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_setting_post
  # 添加用户配置项
  # 添加新的用户配置项
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [UserSetting] :user_setting 配置项内容
  # @return [UserSettingPostResultApiResponse]
  describe 'user_setting_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_setting_put
  # 更新用户配置项
  # 根据配置项ID更新用户配置项内容
  # @param id 配置项ID
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [UserSetting] :user_setting 配置项内容
  # @return [BooleanApiResponse]
  describe 'user_setting_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_settings
  # 获取用户配置列表
  # 根据用户ID、配置项代码和标签获取用户配置列表
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :user_id 用户ID
  # @option opts [String] :code 配置项代码
  # @option opts [String] :tag 配置项标签
  # @return [UserSettingListApiResponse]
  describe 'user_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
