=begin
#用户全部 API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ZSGFClient::UserCurrencyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserCurrencyApi' do
  before do
    # run before each test
    @api_instance = ZSGFClient::UserCurrencyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserCurrencyApi' do
    it 'should create an instance of UserCurrencyApi' do
      expect(@api_instance).to be_instance_of(ZSGFClient::UserCurrencyApi)
    end
  end

  # unit tests for user_currencies
  # 获取用户资产
  # 获取用户的资产列表
  # @param app_key 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @return [UserCurrencyListApiResponse]
  describe 'user_currencies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_currency_consume
  # 消费虚拟币
  # 根据提供的参数进行虚拟币消费
  # @param nonce 随机数
  # @param timestamp 时间戳（允许与服务器时间误差在1分钟内）
  # @param signature 签名
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [CurrencyConsumeRequest] :currency_consume_request 消费请求参数
  # @return [BooleanApiResponse]
  describe 'user_currency_consume test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_currency_exchange
  # 兑换虚拟币
  # 根据提供的参数进行虚拟币兑换
  # @param nonce 随机数
  # @param timestamp 时间戳（允许与服务器时间误差在1分钟内）
  # @param signature 签名
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [ExchangeCurrencyRequest] :exchange_currency_request 兑换请求参数
  # @return [BooleanApiResponse]
  describe 'user_currency_exchange test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_currency_recharge
  # 充值虚拟币
  # 根据提供的参数进行虚拟币充值
  # @param nonce 随机数
  # @param timestamp 时间戳（允许与服务器时间误差在1分钟内）
  # @param signature 签名
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :user_id 
  # @option opts [RechargePointRequest] :recharge_point_request 充值请求参数
  # @return [BooleanApiResponse]
  describe 'user_currency_recharge test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for user_currency_transactions
  # 虚拟币交易记录
  # 根据提供的参数获取虚拟币交易记录
  # @param app_key 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :trans_type 交易类型
  # @option opts [String] :cur_code 货币代码
  # @option opts [Time] :start_time 开始时间
  # @option opts [Time] :end_time 结束时间
  # @option opts [Integer] :skip 跳过的条数
  # @option opts [Integer] :take 拉取的条数
  # @option opts [String] :user_id 
  # @return [UserCurrencyCurrencyTransResultApiResponse]
  describe 'user_currency_transactions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
