=begin
#用户全部 API 文档

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.13.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ZSGFClient::AppUserResetPhoneRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ZSGFClient::AppUserResetPhoneRequest do
  let(:instance) { ZSGFClient::AppUserResetPhoneRequest.new }

  describe 'test an instance of AppUserResetPhoneRequest' do
    it 'should create an instance of AppUserResetPhoneRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ZSGFClient::AppUserResetPhoneRequest)
    end
  end

  describe 'test attribute "phone"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
